swagger: "2.0"
info:
  description: "ReCiter API"
  version: "1.0.0"
  title: "ReCiter API"
  termsOfService: "https://github.com/wcmc-its/ReCiter"
  contact:
    email: "jie265@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "wcmc-its-reciter-service.us-west-2.elasticbeanstalk.com"
basePath: "/v1"
tags:
schemes:
- "http"
paths:
definitions:
  AuthorName:
    type: "object"
    properties:
      firstName:
        type: "string"
      firstInitial:
        type: "string"
      middleName:
        type: "string"
      middleInitial:
        type: "string"
      lastName:
        type: "string"
  KnownRelationship:
    type: "object"
    properties:
      uid:
        type: "string"
      name:
        $ref: '#/definitions/AuthorName'
      type:
        type: "string"
  Education:
    type: "object"
    properties:
      bachelorYear:
        type: "integer"
        format: "int32"
      doctoralYear:
        type: "integer"
        format: "int32"
  PubMedAlias:
    type: "object"
    properties:
      pmid:
        type: "integer"
        format: "int64"
      authorName:
        $ref: '#/definitions/AuthorName'
  Identity:
    type: "object"
    properties:
      uid:
        type: "string"
      primaryName:
        $ref: '#/definitions/AuthorName'
      alternateNames:
        type: "array"
        items:
          $ref: '#/definitions/AuthorName'
      emails:
        type: "array"
        items:
          type: "string"
      knownRelationships:
        type: "array"
        items:
          $ref: '#/definitions/KnownRelationship'
      departments:
        type: "array"
        items:
          type: "string"
      title:
        type: "string"
      institutions:
        type: "array"
        items:
          type: "string"
      degreeYear:
        $ref: '#/definitions/Education'
      personTypes:
        type: "array"
        items:
          type: "string"
      program:
        type: "string"
      boardCertifications:
        type: "array"
        items:
          type: "string"
      citizenship:
        type: "string"
      grants:
        type: "array"
        items:
          type: "string"
      keywords:
        type: "array"
        items:
          type: "string"
      pubMedAlias:
        type: "array"
        items:
          $ref: '#/definitions/PubMedAlias'
      dateInitialRun:
        type: "string"
        format: "date-time"
      dateLastRun:
        type: "string"
        format: "date-time"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"